"""Process Histogram comparing data generated by Matlab and Python script."""

import os.path
import numpy as np
import matplotlib.pyplot as plt

DIR_PATH = os.path.dirname(__file__)

if __name__ == '__main__':
    num_events = 1000
    matlab_data = np.loadtxt(DIR_PATH + '/../results/mathlab/{}ruidoTileOcup100.txt'.format(num_events))
    script_data = np.loadtxt(DIR_PATH + '/../results/noises/{}-events/TileNoiseProbability100.txt'.format(num_events))

    script_data_mean = np.mean(script_data)
    script_data_std = np.std(script_data)

    matlab_data_mean = np.mean(matlab_data)
    matlab_data_std = np.std(matlab_data)

    fig, ((ax0, ax1)) = plt.subplots(nrows=1, ncols=2)


    fig.suptitle('{} events'.format(num_events), fontsize=14)
    ax0.hist(matlab_data, bins="auto", density=True, histtype='bar')
    ax0.legend(prop={'size': 10})
    ax0.grid(axis='y', alpha=0.75)
    ax0.set_title('Matlab Script Noise \n Mean: {:.5f} \n STD: {:.5f}'
                  .format(matlab_data_mean, matlab_data_std))

    ax0.set_xlim(0, 1100)
    ax0.set_ylim(0, 0.005)

    ax1.hist(script_data, bins="auto", density=True, histtype='bar')
    ax1.legend(prop={'size': 10})
    ax1.grid(axis='y', alpha=0.75)
    ax1.set_title('Python Script Noise\nMean: {:.5f}\nSTD: {:.5f}'
                  .format(script_data_mean, script_data_std))
    ax1.set_xlim(0, 1100)
    ax1.set_ylim(0, 0.005)

    plt.show()
